python -m kafker register -n markus
python -m kafker register -n fanboy
python -m kafker register -n nena
python -m kafker register -n rkelly
sleep 3s

python -m kafker follow -a fanboy -p markus --follow
python -m kafker follow -a fanboy -p nena --follow
python -m kafker follow -a markus -p nena --follow

python -m kafker post -a markus -t "Coffee is good."
python -m kafker post -a markus -t "Coffee is even better."
python -m kafker post -a markus -t "Why not Zoidberg?"
python -m kafker post -a markus -t "Mein Maserati fährt 210."
python -m kafker post -a nena -t "99 Luftballons auf ihrem Weg zum Horizont..."
python -m kafker follow -a fanboy -p nena --unfollow
python -m kafker follow -a fanboy -p nena --follow
python -m kafker post -a nena -t "... hielt man für Ufos aus dem all..."
python -m kafker post -a nena -t "... darum schickte ein General..."

python -m kafker post -a rkelly -t "I used to think that I could not go on"
python -m kafker post -a rkelly -t "And life was nothing but an awful song"
python -m kafker post -a rkelly -t "But now I know the meaning of true love"
python -m kafker post -a rkelly -t "I'm leaning on the everlasting arms"
python -m kafker post -a rkelly -t "If I can see it, then I can do it"
python -m kafker post -a rkelly -t "If I just believe it, there's nothing to it"
python -m kafker post -a rkelly -t "I believe I can fly"
python -m kafker post -a rkelly -t "I believe I can touch the sky"
python -m kafker post -a rkelly -t "I think about it every night and day"
python -m kafker post -a rkelly -t "Spread my wings and fly away"
python -m kafker post -a rkelly -t "I believe I can soar"
python -m kafker post -a rkelly -t "I see me running through that open door"
python -m kafker post -a rkelly -t "I believe I can fly"
python -m kafker post -a rkelly -t "I believe I can fly"
python -m kafker post -a rkelly -t "I believe I can fly (woo)"
python -m kafker post -a rkelly -t "See I was on the verge of breaking down"
python -m kafker post -a rkelly -t "Sometimes silence can seem so loud"
python -m kafker post -a rkelly -t "There are miracles in life I must achieve"
python -m kafker post -a rkelly -t "But first I know it starts inside of me, ho-oh"
python -m kafker post -a rkelly -t "If I can see it (woo), then I can be it"
python -m kafker post -a rkelly -t "If I just believe it, there's nothing to it"
python -m kafker post -a rkelly -t "I believe I can fly"
python -m kafker post -a rkelly -t "I believe I can touch the sky"
python -m kafker post -a rkelly -t "I think about it every night and day"
python -m kafker post -a rkelly -t "Spread my wings and fly away"
python -m kafker post -a rkelly -t "I believe I can soar"
python -m kafker post -a rkelly -t "I see me running through that open door"
python -m kafker post -a rkelly -t "I believe I can fly"
python -m kafker post -a rkelly -t "I believe I can fly"
python -m kafker post -a rkelly -t "Oh, I believe I can fly (woo)"
python -m kafker post -a rkelly -t "Hey, 'cause I believe in me"
python -m kafker post -a rkelly -t "Ohh"
python -m kafker post -a rkelly -t "If I can see it (woo), then I can do it (I can do it)"
python -m kafker post -a rkelly -t "If I just believe it, there's nothing to it (hey!)"
python -m kafker post -a rkelly -t "I believe I can fly (woo!)"
python -m kafker post -a rkelly -t "I believe I can touch the sky"
python -m kafker post -a rkelly -t "I think about it every night and day"
python -m kafker post -a rkelly -t "Spread my wings and fly away"
python -m kafker post -a rkelly -t "I believe I can soar"
python -m kafker post -a rkelly -t "I see me running through that open door"
python -m kafker post -a rkelly -t "I believe I can fly (I can fly)"
python -m kafker post -a rkelly -t "I believe I can fly (I can fly)"
python -m kafker post -a rkelly -t "I believe I can fly (I can fly)"
python -m kafker post -a rkelly -t "Hey, if I just spread my wings (I can fly)"
python -m kafker post -a rkelly -t "I can fly (I can fly)"
python -m kafker post -a rkelly -t "I can fly (I can fly)"
python -m kafker post -a rkelly -t "I can fly, hey (I can fly)"
python -m kafker post -a rkelly -t "If I just spread my wings (I can fly)"
python -m kafker post -a rkelly -t "I can fly (I can fly, I can fly)"
python -m kafker post -a rkelly -t "(Woo!) (I can fly)"
python -m kafker post -a rkelly -t "Fly-eye-eye"
